# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9aa677f0e3884c305a1ba8df362fb143b150f66ecb7e0ac9adb675064864b02c7606e3ca330fd0931a80c4a883ea6ec3bc767596f0c3f1ba4278c3a479a4aa0

test:
  secret_key_base: 967bc9970c62ff4dee116a8c57e30fd2f6d244334fc568217be964f0405f9e28d716ccafa47d27f68db0b53745259a959965c9afda90d8db1ec16e4810dd269d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
